<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TelnetFilter.fs" />
    <Compile Include="McpFilter.fs" />
    <Compile Include="BridgeHandler.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
